# Generated by Django 5.0.2 on 2024-02-29 17:39

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniconnectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
