# Generated by Django 5.0.2 on 2024-02-29 17:40

import django_google_maps.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniconnectapp', '0002_alter_university_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='location',
            field=django_google_maps.fields.AddressField(max_length=255),
        ),
    ]
