# Generated by Django 5.0.2 on 2024-02-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniconnectapp', '0003_alter_university_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
