# Generated by Django 5.0.2 on 2024-02-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniconnectapp', '0004_alter_university_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
